function xReturn = addList(obj,args0,args1,args2,args3)
%addList(obj,args0,args1,args2,args3)
%
%     Input:
%       args0 = (string)
%       args1 = (string)
%       args2 = (string)
%       args3 = (int)
%   
%     Output:
%       return = (double)

% Build up the argument lists.
values = { ...
   args0, ...
   args1, ...
   args2, ...
   args3, ...
   };
names = { ...
   'args0', ...
   'args1', ...
   'args2', ...
   'args3', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://service.session.sample', ...
    'addList', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'urn:addList', ...
    soapMessage);
xReturn = parseSoapResponse(response);
