function xReturn = getTermClusterReport(obj,args0,args1,args2,args3,args4)
%getTermClusterReport(obj,args0,args1,args2,args3,args4)
%
%     Input:
%       args0 = (int)
%       args1 = (int)
%       args2 = (int)
%       args3 = (double)
%       args4 = (int)
%   
%     Output:
%       return{:} = ()

% Build up the argument lists.
values = { ...
   args0, ...
   args1, ...
   args2, ...
   args3, ...
   args4, ...
   };
names = { ...
   'args0', ...
   'args1', ...
   'args2', ...
   'args3', ...
   'args4', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}double', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://service.session.sample', ...
    'getTermClusterReport', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'urn:getTermClusterReport', ...
    soapMessage);
xReturn = parseSoapResponse(response);
