function xReturn = loadTesting(obj,args0,args1,args2,args3,args4,args5)
%loadTesting(obj,args0,args1,args2,args3,args4,args5)
%
%     Input:
%       args0 = (string)
%       args1 = (string)
%       args2 = (string)
%       args3 = (int)
%       args4 = (string)
%       args5 = (string)
%   
%     Output:
%       return = (string)

% Build up the argument lists.
values = { ...
   args0, ...
   args1, ...
   args2, ...
   args3, ...
   args4, ...
   args5, ...
   };
names = { ...
   'args0', ...
   'args1', ...
   'args2', ...
   'args3', ...
   'args4', ...
   'args5', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://service.session.sample', ...
    'loadTesting', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'urn:loadTesting', ...
    soapMessage);
xReturn = parseSoapResponse(response);
